---
- name: Ensure config directory exists
  file:
    path: "{{ teku_config_dir }}"
    state: directory
    owner: "{{ teku_user }}"
    group: "{{ teku_group }}"
    recurse: yes
  become: true

- name: Configuration file - monolith
  block:
  - name: Remove stanalone validator config file
    file:
      path: "{{ teku_validator_config_file }}"
      state: absent
    become: true

  - name: Generate config file - monolith
    template:
      src: "{{ teku_config_template }}"
      dest: "{{ teku_monolith_config_file }}"
      owner: "{{ teku_user }}"
      group: "{{ teku_group }}"
    become: true
    notify:
      - restart_teku
  when: "not teku_standalone_validator"

- name: Generate config file - standalone
  block:
    # Set empty list for key and password files to remove the configuration for beacon in standalone mode
    - name: Configuration file - beacon
      template:
        src: "{{ teku_config_template }}"
        dest: "{{ teku_beacon_config_file }}"
        owner: "{{ teku_user }}"
        group: "{{ teku_group }}"
      become: true
      notify:
        - restart_teku
      vars:
        teku_metrics_port: "{{ teku_beacon_metrics_port }}"
        teku_validator_key_files: []
        teku_validator_key_password_files: []

    - name: Configuration file - validator
      template:
        src: "{{ teku_config_template }}"
        dest: "{{ teku_validator_config_file }}"
        owner: "{{ teku_user }}"
        group: "{{ teku_group }}"
      become: true
      notify:
        - restart_teku_validator
      vars:
        teku_metrics_port: "{{ teku_validator_metrics_port }}"

  when: "teku_standalone_validator"

# TODO: add this in when Teku supports the data dir option - see the pre_install file for now
#- name: Create data directory
#  file:
#    path: "{{ teku_data_dir }}"
#    state: directory
#    owner: "{{ teku_user }}"
#    group: "{{ teku_group }}"
#    recurse: yes
#  become: true