---

- name: Install | Setup logrotate
  template:
    src: "logrotate/teku"
    dest: "/etc/logrotate.d/teku"
  become: true

- name: Install | Extract Teku source to install directory
  unarchive:
    src: "{{ teku_download_url }}"
    remote_src: true
    dest: "{{ teku_install_dir }}"
    owner: "{{ teku_user }}"
    group: "{{ teku_group }}"
    mode: '0775'
    extra_opts:
      - --strip-components
      - '1'
  become: true

- name: Install | Create a symlink to current
  file:
    src: "{{ teku_install_dir }}/"
    dest: "{{ teku_current_dir }}"
    state: link
  become: true
