---
- name: Include prepare tasks
  include_tasks: "prepare.yml"

- name: Include network tasks
  include_tasks: "network.yml"
  when: not teku_host_ip

- name: Include install tasks
  include_tasks: "install.yml"

- name: Include monolith configuration tasks
  include_tasks: 'config-monolith.yml'
  when: "not teku_standalone_validator"

- name: Include standalone configuration tasks
  include_tasks: 'config-standalone.yml'
  when: "teku_standalone_validator"

- name: Include monolith service tasks
  include_tasks: "service-monolith.yml"
  when: "not teku_standalone_validator"

- name: Include standalone service tasks
  include_tasks: "service-standalone.yml"
  when: "teku_standalone_validator"