---

# If standalone validator service file exist, it is assumed system has
# been running as standalone validator mode and switching to monolith
# validator mode. Stop standalone beacon and validator services and remove
# standalone validator and beacon service files.

- name: Service Monolith | Check standalone validator service file exist
  stat:
    path: "{{ teku_validator_service_file }}"
  register: teku_standalone_validator_svc_file_stat

- name: Service Monolith | Stop and remove standalone validator service
  block:
  - name: Service Monolith | Stop standalone validator service
    systemd:
      name: "{{ teku_validator_service_name }}"
      state: stopped
      enabled: no
    become: true

  - name: Service Monolith | Remove standalone validator systemd file
    file:
      path: "{{ teku_validator_service_file }}"
      state: absent
    become: true

  when: "teku_standalone_validator_svc_file_stat.stat.exists"


- name: Service Monolith | Check standalone beacon service file exist
  stat:
    path: "{{ teku_beacon_service_file }}"
  register: teku_standalone_beacon_svc_file_stat

- name: Service Monolith | Stop and remove standalone beacon service
  block:
  - name: Service Monolith | Stop standalone beacon service
    systemd:
      name: "{{ teku_beacon_service_name }}"
      state: stopped
    become: true

  - name: Service Monolith | Remove standalone beacon systemd files
    file:
      path: "{{ teku_beacon_service_file }}"
      state: absent
    become: true

  when: "teku_standalone_beacon_svc_file_stat.stat.exists"


# Notify service restart. For first time installation also restart
# service will start the service
- name: Service Monolith | Create Teku monolith systemd service
  template:
    src: "{{ teku_systemd_template }}"
    dest: "{{ teku_monolith_service_file }}"
    owner: "root"
    group: "root"
  become: true
  when:
    - teku_managed_service
  notify:
    - restart_teku_monolith

- name: Service Monolith | Reload systemd config
  systemd:
    daemon_reload: yes
  become: true

- name: Service Monolith | Start teku monolith
  service:
    name: "{{ teku_monolith_service_name }}"
    state: started
    enabled: True
  become: True
